version: '3.3'
services:
  app:
    image: 192.168.100.3:5000/golangswarmapi
    build: .
    ports: 
      - 8007:8007 
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure  
    depends_on:
      - postgres          
    networks:
      - network-api


  postgres:
    image: 192.168.100.3:5000/golangswarmpostgres
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure 
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - network-api
    
  pgadmin:
    image: 192.168.100.3:5000/golangswarmpgadmin
    build: .
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - network-api
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  network-api:
    driver: overlay
