version: '3'
services:
  app:
    container_name: golangswarmapi
    build: .
    ports: 
      - 8007:8007 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - swarmpostgres          
    networks:
      - network-api


  swarmpostgres:
    image: postgres:latest
    container_name: golangswarmpostgres
    restart: always
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - network-api

 

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  network-api:
    driver: overlay
