version: '3'
services:
  app:
    container_name: golangswarmapi
    build: .
    ports: 
      - 8007:8007 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres          
    networks:
      - network-api


  postgres:
    image: postgres:latest
    container_name: go-db
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - network-api
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:85"
    networks:
      - network-api
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  network-api:
    driver: bridge
