version: '3.3'
services:
  app:
    image: 127.0.0.1:5000/golangswarmapi_app:latest
    ports: 
      - 8007:8007 
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure  
    depends_on:
      - swarmpostgres          
    networks:
      - network-api


  swarmpostgres:
    image: 127.0.0.1:5000/golangswarmpostgres_app:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure 
    environment:
      - POSTGRES_USER=${db_user}  
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - network-api
  
  

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  network-api:
    driver: overlay
